In [49]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle


In [50]:
data = pd.read_csv(r"C:\Users\JahnaviNalaJala\Documents\gen ai vs code\13-project -ANN-Tensor, kesra\annclassification\Churn_Modelling.csv")
data.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [51]:
data = data.drop(["RowNumber","CustomerId","Surname"], axis = 1)


In [52]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [53]:
label_encoder = LabelEncoder()
data["Gender"] = label_encoder.fit_transform(data["Gender"])
data


CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [54]:
get_onehot_encoder = OneHotEncoder()
geo_encoder = get_onehot_encoder.fit_transform(data[["Geography"]])
geo_encoder=geo_encoder.toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [55]:
get_onehot_encoder.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [56]:
geo_encoder_df = pd.DataFrame(geo_encoder,columns=get_onehot_encoder.get_feature_names_out(["Geography"]) )
geo_encoder_df.head()

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [57]:
data = pd.concat([data.drop("Geography",axis=1) ,geo_encoder_df],axis =1)
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [58]:
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)

In [59]:
with open("get_onehot_encoder.pkl", "wb") as file:
    pickle.dump(get_onehot_encoder,file)

In [60]:
X = data.drop('Exited', axis=1) # indepedent feacture 
y = data["Exited"]# depedent fecture 

In [61]:
X_train, X_test , y_train, y_test = train_test_split(X,y ,test_size = 0.2, random_state=42 )

In [62]:
stand = StandardScaler()
X_train = stand.fit_transform(X_train)
X_test = stand.transform(X_test)

In [63]:
with open("stand.pkl","wb") as file:
    pickle.dump(stand, file)

## ANN Implematition 

In [64]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [65]:
(X_train.shape[1],)

(12,)

In [66]:
model = Sequential([
    Dense(64, activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32, activation= "relu"),
    Dense(1, activation="sigmoid")
]
)
model.summary()

c:\Users\JahnaviNalaJala\Documents\gen ai vs code\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
LOSS = tf.keras.losses.BinaryCrossentropy()

In [68]:
model.compile(optimizer=opt,loss = LOSS,metrics=["accuracy"] )

In [79]:

import datetime
import os
log_dir = os.path.join("logs", f"fits_{int(tf.timestamp().numpy())}")  
os.makedirs(log_dir, exist_ok=True)
print("Log Directory:", log_dir)  # Debugging check


tensorflow_callbacks = TensorBoard(log_dir= log_dir, histogram_freq=1)

Log Directory: logs\fits_1741127169


In [83]:
elary_stopping = EarlyStopping(monitor="val_loss",patience = 10 , restore_best_weights=True)

In [84]:
history = model.fit(X_train, y_train,validation_data=(X_test,y_test),
                    epochs= 100, callbacks=[tensorflow_callbacks,elary_stopping])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8664 - loss: 0.3274 - val_accuracy: 0.8580 - val_loss: 0.3439
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3296 - val_accuracy: 0.8585 - val_loss: 0.3432
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3306 - val_accuracy: 0.8565 - val_loss: 0.3526
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8689 - loss: 0.3226 - val_accuracy: 0.8635 - val_loss: 0.3596
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8615 - loss: 0.3262 - val_accuracy: 0.8620 - val_loss: 0.3518
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8721 - loss: 0.3243 - val_accuracy: 0.8610 - val_loss: 0.3559
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8636 - loss: 0.3317 - val_accuracy: 0.8635 - val_loss: 0.3500
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8683 - loss: 0.3108 - val_accu

In [85]:
import os

log_dir = "logs/fits_1741127169"
  # Use the correct log directory from your output
print("Existing Log Files:", os.listdir(log_dir))

Existing Log Files: ['train', 'validation']


In [86]:
model.save("model.h5")

In [89]:
import tensorboard
%load_ext tensorboard


The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [91]:
!kill 18776  # Use the process ID from your screenshot (change if needed)
%tensorboard --logdir logs/

kill: 18776: No such process
kill: illegal pid: #
kill: illegal pid: Use
kill: illegal pid: the
kill: illegal pid: process
kill: illegal pid: ID
kill: illegal pid: from
kill: illegal pid: your
kill: illegal pid: screenshot
kill: illegal pid: (change
kill: illegal pid: if
kill: illegal pid: needed)


Reusing TensorBoard on port 6006 (pid 1804), started 0:00:25 ago. (Use '!kill 1804' to kill it.)

In [92]:
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np

In [94]:
model = load_model("model.h5")
with open("get_onehot_encoder.pkl","rb") as file:
    one_hotencoder_geo = pickle.load(file)
with open("label_encoder.pkl","rb") as file:
    label_encoder = pickle.load(file)
with open("stand.pkl", "rb") as file:
    scaler = pickle.load(file)

In [95]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [96]:
# One-hot encode 'Geography'
geo_encoded = one_hotencoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hotencoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df


c:\Users\JahnaviNalaJala\Documents\gen ai vs code\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [97]:
input_df=pd.DataFrame([input_data])
input_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [98]:
input_df['Gender']=label_encoder.transform(input_df['Gender'])
input_df

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [99]:
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [100]:
input_scaled= scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [101]:
pre = model.predict(input_scaled)
pre

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step


array([[0.06857351]], dtype=float32)

In [103]:
pre_prob = pre[0][0]

In [104]:
if pre_prob > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.
